Models/CustomerTB.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AjaxDataTable.Models
{
    public class CustomerTB
    {
        [Key]
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PhoneNo { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace AjaxDataTable.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CustomerTBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AjaxDataTable.Data;
using AjaxDataTable.Models;
using Microsoft.AspNetCore.Mvc;

namespace AjaxDataTable.Controllers
{
    public class CustomerTBController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomerTBController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.CustomerTBs.ToList());
        }

        public JsonResult GetAllCustomers()
        {
            List<CustomerTB> customerTBs = new List<CustomerTB>();
            customerTBs = _context.CustomerTBs.Select(c => c).ToList();
            return Json(new { data = customerTBs });
            
        }


        public IActionResult ShowTable()
        {
            return View();
        }


        [HttpPost]
        public IActionResult LoadData()
        {
            try
            {
                var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;
                var customerData = (from tempcustomer in _context.CustomerTBs select tempcustomer);
                //Sorting
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                {  
                    //customerData = customerData.OrderBy(sortColumn + " " + sortColumnDirection);
                    switch (sortColumn)
                    {
                        case "CustomerName":
                            customerData = sortColumnDirection == "asc"? customerData.OrderBy(c => c.CustomerName) :  customerData.OrderByDescending(c => c.CustomerName);
                            break;
                        case "Address":
                            customerData = sortColumnDirection == "asc" ? customerData.OrderBy(c => c.Address) : customerData.OrderByDescending(c => c.Address);
                            break;
                        case "City":
                            customerData = sortColumnDirection == "asc" ? customerData.OrderBy(c => c.City) : customerData.OrderByDescending(c => c.City);
                            break;
                        case "Country":
                            customerData = sortColumnDirection == "asc" ? customerData.OrderBy(c => c.Country) : customerData.OrderByDescending(c => c.Country);
                            break;
                        case "PhoneNo":
                            customerData = sortColumnDirection == "asc" ? customerData.OrderBy(c => c.PhoneNo) : customerData.OrderByDescending(c => c.PhoneNo);
                            break;
                        default :                        
                            break;
                    }
                }
                //Search
                if (!string.IsNullOrEmpty(searchValue))
                {
                    customerData = customerData.Where(m => m.CustomerName.Contains(searchValue) ||
                    m.Address.Contains(searchValue) || m.City.Contains(searchValue) ||
                    m.Country.Contains(searchValue) || m.PhoneNo.Contains(searchValue));
                }
                //total number of rows counts
                recordsTotal = customerData.Count();
                //Paging
                var data = customerData.Skip(skip).Take(pageSize).ToList();
                //Return Json Data
                return Json(new { draw, recordsFiltered = recordsTotal, recordsTotal, data });

            }
            catch (Exception)
            {

                throw;
            }

            
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AjaxDataTable.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace AjaxDataTable.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CustomerTB/Index.cshtml
@model IEnumerable<AjaxDataTable.Models.CustomerTB>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CustomerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CustomerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CustomerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/CustomerTB/ShowTable.cshtml
@model IEnumerable<AjaxDataTable.Models.CustomerTB>

@{
    ViewData["Title"] = "Index";
    Layout = null;
}


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />


<div class="row">
    <div class="col-sm-12 ">
        <br />
        <div style="width:90%; margin:0 auto;">
            <table id="customertb" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>City</th>
                        <th>Country</th>
                        <th>Phone Number</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>

            </table>
        </div>
    </div>
</div>


    @*<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap.min.js"></script>*@

    <script>
   $(document).ready(function () {
       $('#customertb').DataTable({
           "processing": true,
           "serverSide": true,
           "filter": true,
           "orderMulti": false,
           "order": [[1, 'asc']],
            "ajax": {
                'url': '@Url.Action("LoadData", "CustomerTB")',
                "type": "POST",
                "datatype": "json"
                },
                "language": {
                "emptyTable": "No record found.",
                "processing":
                '<i class="fa fa-spinner fa-spin fa-3x fa-fw" style="color:#2a2b2b;"></i><span class="sr-only">Loading...</span> '
                },
                "columnDefs": [{
                "targets": [0],
                "visible": false,
                "searchable": false
                }],
                "columns": [
                { "data": "customerId", "name": "CustomerId", "autoWidth": true },
                { "data": "customerName", "name": "CustomerName", "autoWidth": true },
                { "data": "address", "name": "Address", "autoWidth": true },
                { "data": "city", "name": "City", "autoWidth": true },
                { "data": "country", "name": "Country", "autoWidth": true },
                { "data": "phoneNo", "name": "PhoneNo", "autoWidth": true },
                {
                "render": function (data, type, full, meta) {
                return '<a class="btn btn-info" href="/CustomerTB/Edit/' + full.CustomerId + '">Edit</a>';
                }
                },
                {
                data: null,
                render: function (data, type, row) {
                return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + row.CustomerId + "');>Delete</a>" ;
                           }
                           },
                           ],
                           });
                           });
                           function DeleteData(CustomerId) {
                           if (confirm("Are you sure you want to delete ....?")) {
                           Delete(CustomerId);
                           } else {
                           return false;
                           }
                           }
                           function Delete(CustomerId) {
                           var url='@Url.Content("~/")' + "CustomerTB/Delete" ;
                           $.post(url, { ID: CustomerId }, function (data) {
                           if (data) {
                           oTable=$('#customertb').dataTable();
                           oTable.draw();
                           } else {
                           alert("Something went wrong!");
                           }
                           })
                           }



    </script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjaxDataTable</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="CustomerTB" asp-action="Index">AjaxDataTable</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerTB" asp-action="ShowTable">Customer Table</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AjaxDataTable - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>